---
deployment:
  tasks:
    # Set the deployment path to your public_html directory
    - export DEPLOYPATH=/home/$USER/public_html/

    # Copy site files to the deployment path
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp privacy-policy.html $DEPLOYPATH

    - /bin/cp terms-of-service.html $DEPLOYPATH
    - /bin/cp favicon.png $DEPLOYPATH

    # Ensure correct permissions
    # - /bin/chmod 644 $DEPLOYPATH/index.html
    # - /bin/chmod 644 $DEPLOYPATH/styles.css
    # - /bin/chmod 644 $DEPLOYPATH/script.js
    # - /bin/chmod 644 $DEPLOYPATH/privacy-policy.html
    # - /bin/chmod 644 $DEPLOYPATH/terms-of-service.html
    # - /bin/chmod 644 $DEPLOYPATH/favicon.png

